misky_log/urls.py
from django.contrib import admin
from django.urls import path,include

from misky_logs.urls import views


#app_name = 'misky_logs'
#app_name = 'users'

urlpatterns = [
    path('admin/', admin.site.urls),
    #添加默认主页
    #path('',views.index, name='index'),
    path('',include('misky_logs.urls',namespace='misky_logs')),

    #添加用户主页
    path('users/',include('users.urls',namespace='users')),



]

misky_logs/urls.py
'''定义misky_logs的URL模式'''

from django.urls import path

from . import views

app_name = 'misky_logs'

urlpatterns = [
    #主页
    path('',views.index, name='index'),

    #显示所有主题
    path('topics/',views.topics, name="topics"),

    # 添加特定主题的详细页面
    path('topics/(?P<topic_id>\d+)/',views.topic,name='topic'),

    #添加新主题的网页
    path('new_topic/',views.new_topic,name='new_topic'),

    #添加用于新条目的网页
    path('new_entry/(?P<topic_id>\d+)/',views.new_entry,name='new_entry'),

    #添加用于编辑条目的页面
    path('edit_entry/(?P<entry_id>\d+)/',views.edit_entry, name='edit_entry'),
]

users/urls.py
"""为应用程序users定义URL模式"""

from django.urls import path
from django.contrib.auth.views import LoginView

from . import views
app_name = 'users'

#LoginView.template_name = 'users/login.html'

urlpatterns = [
    #path('login/',LoginView.as_view(),name ='login'),
    path('logout/',views.logout_view, name = 'logout')   ,
    path('login/',LoginView.as_view(template_name='users/login.html'),name='login'),
    path('register/',views.register, name ='register'),
]

misky_logs/models.py
from django.db import models

from django.contrib.auth.models import User #导入用户模型

# Create your models here.

#导入了模块models，让我们开始创建模型，模型就是我们学习的类

class Topic(models.Model):
    """用户学习的主题"""
    #我们定义了一个topic的类，它继承了MODEL的属性

    text = models.CharField(max_length=200)  #定义一个text属性，字符或文本，限制了长度（名称，城市等等）
    date_added = models.DateTimeField(auto_now_add=True) #定义一个添加日期，继承了属性，自动设置成当前时间
    owner = models.ForeignKey(User,on_delete=models.DO_NOTHING) #建立一个到模型USER的外间联系

    def __str__(self):
        '''返回模型字符串表示'''
        return self.text #返回上面text的内容

class Entry(models.Model):
    """学到有关某个主题的知识"""

    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    #topic是一个外键的实例，引用数据库中的一条记录
    text = models.TextField()
    #text是一个TEXTFIELD的实例。
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

        #嵌套了一个meta类，用于储存管理模型的额外信息
    def __str__(self):
        """返回模型字符串表示"""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

misky_logs/forms.py
from django import forms

from .models import Topic

from .models import Entry

class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})} #小部件

misky_logs/views.py
from django.shortcuts import render

from .models import Topic
from .models import Entry
from .forms import TopicForm
from .forms import EntryForm

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required #限制访问（装饰器）
from django.http import Http404


# Create your views here.
# 在这里创建视图

def index(request):
    """学习笔记的主页"""

    return render(request,'misky_logs/index.html')

@login_required
#装饰器用于下面topics函数，
#加了个@和login_required，可以让python在运行topics的代码前，先运行login_requied的代码
def topics(request):
    """显示所有的主题"""
    #topics = Topic.objects.order_by('date_added')
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request,'misky_logs/topics.html',context)


@login_required
def topic(request,topic_id):
    """显示单个主题及其条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404 #给它返回异常404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request,"misky_logs/topic.html",context)


@login_required
def new_topic(request):
    """可以添加新主题"""
    if request.method != 'POST':  #未提交数据，创建一个新表单
        form = TopicForm()

    else:
        form = TopicForm(request.POST)  #提交数据，那么就要进行数据处理
        if form.is_valid(): # 验证字段是否符合要求
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save() #保存数据，写入数据库
            return HttpResponseRedirect(reverse('misky_logs:topics')) #浏览器重定向，并且刷新能看见新的主题
    context = {'form':form}
    return render(request,'misky_logs/new_topic.html',context)


@login_required
def new_entry(request,topic_id):
    """在特定主题中添加新的条目"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form  = EntryForm()

    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('misky_logs:topic',args=[topic_id]))
    context = {'topic':topic, 'form':form}
    return render(request,'misky_logs/new_entry.html',context)


@login_required
def edit_entry(request,entry_id):
    """编辑现有的条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404 #给它返回异常404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST) #必输是POST，而不是post
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('misky_logs:topic',args=[topic.id]))
    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request,'misky_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('misky_logs:index'))

def register(request):
    "注册新用户"
    if request.method != 'POST':
        #显示空表单
        form = UserCreationForm()

    else:
        #处理填写好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()

            #让用户自动登录，在重定向到首页
            authticated_user = authenticate(username = new_user.username,
                                            password = request.POST['password1'])
            login(request,authticated_user)
            return HttpResponseRedirect(reverse('misky_logs:index'))

    context = {'form':form}
    return render(request,'users/register.html',context)

misky_logs/templates/misky_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Complatible" content="IE=edge">
    <meta name="viewport" content="width=devive-width,initial-scale=1">

    <title>misky的学习园地</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>


<body>
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'misky_logs:index' %}">
              学习园地</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'misky_logs:topics' %}">主题</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">注销</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">注册</a></li>
              <li><a href="{% url 'users:login' %}">登录</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div>


</body>
</html>

misky_logs/templates/misky_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "misky_logs/base.html" %}

{% block content %}

<p><a href="{% url 'misky_logs:topic' topic.id %}">{{topic}}</a> </p>

<p>编辑记录：</p>

<form action="{% url 'misky_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="提交">保存</button>
</form>
{% endblock content %}
</body>
</html>

misky_logs/templates/misky_logs/index.html
{% extends 'misky_logs/base.html' %}

{% block header %}
  <div class='jumbotron'>
      <h1>心之所往，无可匹及.</h1>
  </div>
{% endblock %}

{% block content %}
 <h2>
    <a href="{% url 'users:register' %}">注册一个账户</a> 玩自己的泥巴.
  </h2>
  <h2>

    学习笔记可以帮助你跟踪学习，可以记录任何主题的信息。
  </h2>

{% endblock content %}
</body>
</html>

misky_logs/templates/misky_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "misky_logs/base.html" %}

{% block content %}

<p><a href="{% url 'misky_logs:topic' topic.id %}">{{topic}}</a> </p>

<p>添加一条新的记录：</p>

<form action="{% url 'misky_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="提交">添加记录</button>
</form>
{% endblock content %}
</body>
</html>

misky_logs/templates/misky_logs/new_topic.html
{% extends "misky_logs/base.html" %}

{% load bootstrap3 %}

{% block header %}
  <h2>添加一个新的主题：</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'misky_logs:new_topic' %}" method="post" class="form-row">

    {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="提交" class="btn btn-primary">添加主题</button>
        {% endbuttons %}
</form>

{% endblock content %}

misky_logs/templates/misky_logs/topic.html
{% extends "misky_logs/base.html" %}



{% block header %}
  <h2>Topic: {{ topic }}</h2>
{% endblock header %}

{% block content %}


<p><a href="{% url 'misky_logs:new_entry' topic.id %}">随手一笔:</a></p>


    {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>

        {{ entry.date_added|date:'M d,Y H:i' }}
            <small>
           <a href="{% url 'misky_logs:edit_entry' entry.id %}">补充完善</a>
            </small>
            </h3>
      </div>

            <div class="panel-body">
        {{ entry.text|linebreaks }}
            </div>


    {% empty %}
    <li>
        there are no entries for this topic yet.
    </li>

            {% endfor %}



{% endblock content %}

misky_logs/templates/misky_logs/topics.html
{% extends "misky_logs/base.html" %}


{% block header %}
<H1>主题</H1>
{% endblock %}

{% block content %}

<ul>
    {% for topic in topics %}
      <li>
          <h3><a href="{% url 'misky_logs:topic' topic.id %}">{{ topic}} </a>
          </h3>

      </li>
    {% empty %}
      <li>还没有添加主题.</li>
    {% endfor %}

</ul>

<h3><a href="{% url 'misky_logs:new_topic' %}">添加主题</a>
</h3>


{% endblock content %}

misky_logs/templates/users/login.html
{% extends "misky_logs/base.html" %}
{% load bootstrap3 %}


{% block header %}
  <h2>登录你的账号...</h2>
{% endblock %}


{% block content %}

  {% if form.errors %}
  <p>账号密码不匹配，请重新输入</p>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}" class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="提交"  class="btn btn-primary">登录</button>
    {% endbuttons %}
      <input type="hidden" name="next" value="{% url 'misky_logs:index' %}" />

  </form>
{% endblock content %}

misky_logs/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "misky_logs/base.html" %}
{% block content %}

<form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button name="提交">注册</button>
    <input type="hidden" name="next" value="{% url 'misky_logs:index' %}" />

</form>
{% endblock content %}
</body>
</html>